# @format

openapi: 3.0.1
info:
  title: Links.co API service
  description: Links.co API service
  version: 1.0.0
  license:
    name: Copyright © 2022 Links.co
  contact:
    name: Links.co
    url: Links.co
    email: info@links.co
servers:
  - url: /api/v1
    description: API URL
tags:
  - name: Authentication
    description: Auth endpoints
paths:
  /auth/register:
    post:
      summary: Save a new user information
      tags:
        - Auth
      requestBody:
        description: Requires the id of the user to be saved to db
        content:
          application/json:
            schema:
              $ref: "#/schemas/SaveUser"
        required: true
      responses:
        "201":
          description: User created
          content: {}
        "400":
          description: Bad request
          content: {}
        "403":
          description: User Exists
          content: {}
        "500":
          description: Server Error
          content: {}
  /auth/login:
    post:
      summary: Login user
      tags:
        - Auth
      requestBody:
        description: Requires email and password
        content:
          application/json:
            schema:
              $ref: "#/schemas/LoginUser"
        required: true
      responses:
        "200":
          description: Login succesful
          content: {}
        "400":
          description: Bad request
          content: {}
        "401":
          description: Login failed
          content: {}
        "500":
          description: Server Error
          content: {}
  /auth/user/{id}:
    get:
      summary: Get a user
      tags:
        - User
      parameters:
        - name: id
          in: path
          example: 1
          description: The id of the user to retrieve
          required: true
          schema:
            type: string
        - name: token
          in: header
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pY2hhZWxuZ2lyaUBnbWFpbC5jb20iLCJkYXRlQ3JlYXRlZCI6IjIwMjItMDgtMjNUMTk6MjY6MzIuMTA2WiIsImlhdCI6MTY2MTI4Mjc5Mn0.F0LfQGuV4mTngIKimqtHkHOdJG86Ut-bxR_3dE-7H9s
          description: Authentication token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User found
          content: {}
        "400":
          description: Bad request
          content: {}
        "404":
          description: User does not exist
          content: {}
        "500":
          description: Server Error
          content: {}
  /link/create:
    post:
      summary: Shorten a url
      tags:
        - Link
      requestBody:
        description: Requires the URL to be shortened
        content:
          application/json:
            schema:
              $ref: "#/schemas/CreateLink"
        required: true
      responses:
        "201":
          description: Link created
          content: {}
        "400":
          description: Bad request
          content: {}
        "403":
          description: Link Exists
          content: {}
        "500":
          description: Server Error
          content: {}
  /link/{id}:
    get:
      summary: Get a Link
      tags:
        - Link
      parameters:
        - name: id
          in: path
          example: 1
          description: The id of the link to retrieve
          required: true
          schema:
            type: string
        - name: token
          in: header
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pY2hhZWxuZ2lyaUBnbWFpbC5jb20iLCJkYXRlQ3JlYXRlZCI6IjIwMjItMDgtMjNUMTk6MjY6MzIuMTA2WiIsImlhdCI6MTY2MTI4Mjc5Mn0.F0LfQGuV4mTngIKimqtHkHOdJG86Ut-bxR_3dE-7H9s
          description: Authentication token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Link found
          content: {}
        "400":
          description: Bad request
          content: {}
        "404":
          description: Link does not exist
          content: {}
        "500":
          description: Server Error
          content: {}
  /link/{id}/delete:
    delete:
      summary: Delete a Link
      tags:
        - Link
      parameters:
        - name: id
          in: path
          description: The id of the link to delete
          required: true
          schema:
            type: string
        - name: token
          in: header
          description: Authentication token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Link found
          content: {}
        "400":
          description: Bad request
          content: {}
        "404":
          description: Link does not exist
          content: {}
        "500":
          description: Server Error
          content: {}
  /link/update:
    patch:
      summary: Shorten a url
      tags:
        - Link
      requestBody:
        description: Requires the URL to be shortened
        content:
          application/json:
            schema:
              $ref: "#/schemas/UpdateLink"
        required: true
      responses:
        "201":
          description: Link updated
          content: {}
        "400":
          description: Bad request
          content: {}
        "403":
          description: Link Exists
          content: {}
        "500":
          description: Server Error
          content: {}
  /{id}/my-links:
    get:
      summary: Get my Links
      tags:
        - Link
      parameters:
        - name: id
          in: path
          example: 1
          description: The id of the user that own the links
          required: true
          schema:
            type: string
        - name: token
          in: header
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pY2hhZWxuZ2lyaUBnbWFpbC5jb20iLCJkYXRlQ3JlYXRlZCI6IjIwMjItMDgtMjNUMTk6MjY6MzIuMTA2WiIsImlhdCI6MTY2MTI4Mjc5Mn0.F0LfQGuV4mTngIKimqtHkHOdJG86Ut-bxR_3dE-7H9s
          description: Authentication token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Link found
          content: {}
        "400":
          description: Bad request
          content: {}
        "404":
          description: Link does not exist
          content: {}
        "500":
          description: Server Error
          content: {}

schemas:
  SaveUser:
    title: create new user
    required:
      - user information
    type: object
    properties:
      firstName:
        type: string
        example: john
      lastName:
        type: string
        example: doe
      email:
        type: string
        example: michaelngiri@gmail.com
      password:
        type: string
        example: secure-password
      phoneNumber:
        type: string
        example: "+12345697890"
  LoginUser:
    title: login a user
    required:
      - user information
    type: object
    properties:
      email:
        type: string
        example: michaelngiri@gmail.com
      password:
        type: string
        example: secure-password
  CreateLink:
    title: create link
    required:
      - Link, user id
    type: object
    properties:
      link:
        type: string
        example: https://links.co/very-long-link-that-needs-to-be-shorter-for-sharing
      userID:
        type: integer
        example: 1
      token:
        type: string
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pY2hhZWxuZ2lyaUBnbWFpbC5jb20iLCJkYXRlQ3JlYXRlZCI6IjIwMjItMDgtMjNUMTk6MjY6MzIuMTA2WiIsImlhdCI6MTY2MTI4Mjc5Mn0.F0LfQGuV4mTngIKimqtHkHOdJG86Ut-bxR_3dE-7H9s
  UpdateLink:
    title: update link
    required:
      - Link id, token
    type: object
    properties:
      newLink:
        type: string
        example: https://links.co/a-new-very-long-link-that-needs-to-be-shorter-for-sharing
      linkID:
        type: integer
        example: 1
      token:
        type: strings
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pY2hhZWxuZ2lyaUBnbWFpbC5jb20iLCJkYXRlQ3JlYXRlZCI6IjIwMjItMDgtMjNUMTk6MjY6MzIuMTA2WiIsImlhdCI6MTY2MTI4Mjc5Mn0.F0LfQGuV4mTngIKimqtHkHOdJG86Ut-bxR_3dE-7H9s
